FROM ubuntu:20.04

ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/

RUN apt-get update -y \
&& apt-get install -y software-properties-common \
&& add-apt-repository ppa:deadsnakes/ppa \
&& apt-get install python3.10 -y \
&& apt-get install openjdk-8-jdk -y \
&& apt-get install python3-pip -y \
&& export JAVA_HOME \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

ENV PYTHONNUNBUFFERED=1
ENV PYSPARK_PYTHON=python3
#ENV PYSPARK_DRIVER_PYTHON=python3

WORKDIR /app
COPY ./app .
RUN pip3 install -r requirements.txt

CMD ["python3", "consumer.py"]